shallow_clone: true

build:
  project: "Build\\vwsi.sln"
  parallel: true
  verbosity: normal

image:
  - Visual Studio 2017

platform: 
  - x64

configuration:
  - Release

environment:
  VULKAN_SDK: "C:\\VulkanSDK\\1.1.77.0\\"

install:
# - git submodule update --init --recursive
  - mkdir C:\Projects\deps
  - cd C:\Projects\deps
  - set CMAKE_URL="https://cmake.org/files/v3.9/cmake-3.9.0-win64-x64.zip"
  - appveyor DownloadFile %CMAKE_URL% -FileName cmake-3.9.0-win64-x64.zip
  - 7z x cmake-3.9.0-win64-x64.zip -oC:\Projects\deps > nul
  - move C:\Projects\deps\cmake-* C:\Projects\deps\cmake
  - set PATH=C:\Projects\deps\cmake\bin;%PATH%
  - cmake --version
  - appveyor DownloadFile https://vulkan.lunarg.com/sdk/download/1.1.77.0/windows/VulkanSDK-1.1.77.0-Installer.exe -FileName vulkan.exe
  - vulkan.exe /S

before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64
  - cd C:\Projects\vwsi
  - mkdir build
  - cd build
  - cmake .. -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=Release -DVWSI_INSTALL=ON -DVWSI_BUILD_TESTING=OFF
  - cmake --build . --config Release
  - cd ../
  - mkdir VWSI
  - mkdir VWSI\include
  - xcopy build\Release\lib\Release VWSI\ /s/h/e/k/f/c
# - xcopy build\Release\include VWSI\include\ /s/h/e/k/f/c
  - xcopy include VWSI\include\ /s/h/e/k/f/c

artifacts:
  - path: vwsi\
    name: VWSI
