matrix:
  include:
    # GCC 7
  - os: linux
    dist: trusty
    sudo: required
    addons: &gcc7
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
        - xorg-dev 
        - libglu1-mesa-dev
        artifacts:
          paths: Build/Release/
    language: cpp
    compiler: gcc
    env:
    - COMPILER=g++-7
    - GSL_CXX_STANDARD=17
    before_install:
    - sudo apt-get -qq update
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  # Clang 6.0
  - os: linux
    dist: trusty
    sudo: required
    addons: &clang60
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-6.0
        - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main'
          key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
        packages:
        - clang-6.0
        - libc++-dev
        - xorg-dev
        - libglu1-mesa-dev
    language: cpp
    compiler: clang
    env:
    - COMPILER=clang++-6.0
    - COMPILER_FLAGS=-stdlib=libc++
    - GSL_CXX_STANDARD=17
    before_install:
    - sudo apt-get -qq update
    - sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-6.0 1000
 # XCode 9.4
  - os: osx
    osx_image: xcode9.4
    sudo: required
    language: cpp
    compiler: clang
    env:
    - COMPILER=clang++
    - GSL_CXX_STANDARD=17
    before_install:
    - brew update
    - brew install cmake || brew upgrade cmake

script:
- cd $TRAVIS_BUILD_DIR
- git submodule update --init --recursive
- mkdir build
- cd build
- |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      curl https://vulkan.lunarg.com/sdk/download/1.1.77.0/linux/vulkansdk-linux-x86_64-1.1.77.0.tar.gz -L -o vulkan.tar.gz
      tar zxf vulkan.tar.gz
      source 1.1.77.0/setup-env.sh
      cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DVWSI_INSTALL=ON -DVWSI_BUILD_TESTING=OFF
    else
      curl https://vulkan.lunarg.com/sdk/download/1.1.77.0/mac/vulkansdk-macos-1.1.77.0.tar.gz -L -o vulkan.tar.gz
      tar zxf vulkan.tar.gz
#     source vulkansdk-macos-1.1.77.0/setup-env.sh
      cmake .. -G "Xcode" -DCMAKE_BUILD_TYPE=Release -DVWSI_INSTALL=OFF -DVWSI_BUILD_TESTING=OFF
    fi
- ls
- |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      make all
    else
      xcodebuild -target vwsi -configuration Release
    fi
- cd ../
